# Generated by Django 3.0.3 on 2020-02-09 16:12

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('width', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('contents', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', jsonfield.fields.JSONField()),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='word_puzzle.Field')),
            ],
        ),
    ]
